### ISSUE TITLE
Intermittent error where disconnect fails 

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-mscalendar#148]
There is an issue I've seen a couple time where `mscalendar disconnect` fails. 
The debug show that the subscription is deleted but then the plugin crashes and the disconnect does not complete.
![DisconnectCrash](https://user-images.githubusercontent.com/35588783/83101892-58d80980-a081-11ea-96ec-2a988f269be5.PNG)

Not sure if it related but I see the following panic occur:
```
{"level":"debug","ts":1590641888.3242419,"caller":"plugin/hclog_adapter.go:53","msg":"panic: runtime error: invalid memory address or nil pointer dereference","plugin_id":"com.mattermost.mscalendar"}
{"level":"debug","ts":1590641888.3242915,"caller":"plugin/hclog_adapter.go:53","msg":"[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xd078c9]","plugin_id":"com.mattermost.mscalendar"}
{"level":"debug","ts":1590641888.3243175,"caller":"plugin/hclog_adapter.go:53","msg":"","plugin_id":"com.mattermost.mscalendar"}
{"level":"debug","ts":1590641888.32433,"caller":"plugin/hclog_adapter.go:53","msg":"goroutine 39 [running]:","plugin_id":"com.mattermost.mscalendar"}
```
Not sure if the log is helpful. Sorry I wasn't able to go back and get more from the log.

This happened on build https://github.com/mattermost/mattermost-plugin-mscalendar/pull/120/commits/364913f96f7f92186a68aac710c357308001bd24

After restarting the plugin and trying to disconnect the user again. This issue no longer reproduced.

**Comment by larkox** [comment]
Panics usually give a whole stack trace of all the functions called to reach that panic. Not sure if they also appear in that view, but should be just the following lines (a few of them).

Usually, the shape of the lines is something like:
```
github.com/mattermost/mattermost-plugin-mscalendar/some/path.(objectname).functionname(gibberish)
github.com/mattermost/mattermost-plugin-mscalendar/some/path:lineNumber
...
```

If you have by any chance that stack trace, it would be really helpful to pinpoint the issue.
